version: "3.2"

services:
  server:
    image: longestline:server
    container_name: longestline-server
    build:
      dockerfile: docker/dev/.Dockerfile
      context: ./server
    volumes:
      - "./server:/server"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    links:
      - mongodb
    stdin_open: true
    tty: true

  mongodb:
    image: longestline:mongodb
    container_name: longestline-mongodb
    build:
      dockerfile: docker/dev/.Dockerfile
      context: ./mongodb
    ports:
      - "27017:27017"
    volumes:
      - "./mongodb/data:/data"
