version: "3.2"

services:

  server:
    image: longestline:server
    container_name: longestline-server
    environment:
      - SECRET_KEY=xxxx-xxxx-xxxx-xxxx
      - DEBUG=True
    build:
      dockerfile: docker/dev/.Dockerfile
      context: ./server
    volumes:
      - "./server:/server"
    ports:
      - "8080:8080"
    depends_on:
      - database
      - redis
    links:
      - database
      - redis
    stdin_open: true
    tty: true

  app:
    image: longestline:app
    container_name: longestline-app
    build:
      dockerfile: docker/dev/.Dockerfile
      context: ./app
    volumes:
      - "./app:/app"
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  database:
    container_name: longestline-database
    image: longestline:database
    build:
      dockerfile: docker/dev/.Dockerfile
      context: ./database
    expose:
      - "5432"
    environment:
      PGDATA: /data
    volumes:
      - database:/data

  proxy:
    image: longestline:proxy
    container_name: longestline-proxy
    build:
      dockerfile: docker/dev/.Dockerfile
      context: ./proxy
    depends_on:
      - server
      - app
    links:
      - server
      - app
    ports:
      - "80:80"
      - "443:443"

  redis:
    container_name: longestline-redis
    image: longestline:redis
    build:
      dockerfile: docker/dev/.Dockerfile
      context: ./redis
    expose:
      - "6379"
    volumes:
      - redis:/data

volumes:
  database:
  redis:
