# Generated by Django 2.2.1 on 2019-05-19 15:49

import api_game.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', djongo.models.fields.EmbeddedModelField(model_container=api_game.models.Description, null=True)),
                ('turns', djongo.models.fields.ArrayModelField(model_container=api_game.models.Turn)),
                ('state', djongo.models.fields.EmbeddedModelField(model_container=api_game.models.State, null=True)),
                ('field', djongo.models.fields.EmbeddedModelField(model_container=api_game.models.Field, null=True)),
            ],
        ),
    ]
